# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('login_user', models.AutoField(primary_key=True, serialize=False)),
                ('login_pass', models.CharField(max_length=12)),
            ],
        ),
    ]
